---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Include OS-specific variables (Amazon Linux)
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}.yml"
  when: ansible_facts['distribution'] == 'Amazon'

- name: Install Java OpenJDK
  ansible.builtin.package:
    name: "{{ installed_packages }}"
    state: present
  become: true
