---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific variables (Amazon Linux)
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Amazon'

- name: Install Java OpenJDK
  ansible.builtin.package:
    name: "{{ installed_packages }}"
    state: present
  become: true
